import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Deploy Button Configurations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Deploy button with no extra settings</h2>
        <a
          href="https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fvercel%2Fnext.js%2Ftree%2Fcanary%2Fexamples%2Fhello-world"
          target="_blank"
        >
          <img src="https://vercel.com/button" alt="Deploy with Vercel" />
        </a>
        <h2>Deploy button with root directory</h2>
        <a
          href="https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fvercel-support%2Fyarn-ws-monorepo&root-directory=apps%2Ffrontend"
          target="_blank"
        >
          <img src="https://vercel.com/button" alt="Deploy with Vercel" />
        </a>
        <h2>Deploy button with Build command</h2>
        <a
          href="https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fvercel%2Fnext.js%2Ftree%2Fcanary%2Fexamples%2Fhello-world&build-command=npm%20run%20build"
          target="_blank"
        >
          <img src="https://vercel.com/button" alt="Deploy with Vercel" />
        </a>
      </main>
    </div>
  );
}
